### ISSUE TITLE
Reader won't go back to first word after reaching end of Document and pressing play

### ISSUE THREAD

**Issue by Dachkar** [dsarlo/word-by-word#37] opened 2019-01-30 00:49 UTC
Tried fixing by adding a CheckIfAtEnd() inside ReadSelectedDocumentWordsAsync, but that was unsucessful.

**Comment by dsarlo** [comment] 2019-01-31 20:32
There is an empty character at the end of every single _wordsToRead list...

**Comment by dsarlo** [comment] 2019-01-31 20:35
This is also not intended behavior. Closing this issue. The user is supposed to reset back to the beginning if they'd like.

**Closed as completed** 2019-01-31 20:35 UTC
Labels: wontfix, denied
